#!/usr/bin/env node
// Fetches a 10×10 elevation grid centred on Svyatogorovo from OpenTopoData
// and writes src/topo-data.js with the normalised height matrix.

import { writeFileSync } from "fs";
import { fileURLToPath } from "url";
import { dirname, resolve } from "path";

const __dirname = dirname(fileURLToPath(import.meta.url));

const ROWS = 10;
const COLS = 10;
const CENTER_LAT = 56.404361;
const CENTER_LON = 37.821090;
const SPAN_LAT = 0.14;   // degrees north–south
const SPAN_LON = 0.20;   // degrees east–west

const locations = [];
for (let r = 0; r < ROWS; r++) {
  for (let c = 0; c < COLS; c++) {
    const lat = CENTER_LAT + SPAN_LAT / 2 - (r / (ROWS - 1)) * SPAN_LAT;
    const lon = CENTER_LON - SPAN_LON / 2 + (c / (COLS - 1)) * SPAN_LON;
    locations.push(`${lat.toFixed(6)},${lon.toFixed(6)}`);
  }
}

const url = `https://api.opentopodata.org/v1/srtm30m?locations=${locations.join("|")}`;
console.log(`Fetching ${ROWS * COLS} elevation points…`);

const res = await fetch(url);
if (!res.ok) throw new Error(`HTTP ${res.status}: ${await res.text()}`);
const data = await res.json();

if (data.status !== "OK") throw new Error(`API error: ${JSON.stringify(data)}`);

const elevations = data.results.map(r => r.elevation);
const min = Math.min(...elevations);
const max = Math.max(...elevations);
console.log(`Elevation range: ${min}m – ${max}m`);

// normalise 0–1, preserve two decimal places
const grid = [];
for (let r = 0; r < ROWS; r++) {
  const row = [];
  for (let c = 0; c < COLS; c++) {
    const raw = elevations[r * COLS + c];
    row.push(parseFloat(((raw - min) / (max - min)).toFixed(3)));
  }
  grid.push(row);
}

const out = `// Auto-generated by scripts/gen-topo.js — do not edit manually
// Elevation grid: ${ROWS}×${COLS}, centre ${CENTER_LAT},${CENTER_LON}
// Source: OpenTopoData SRTM30m, range ${min}m–${max}m

export const TOPO_ROWS = ${ROWS};
export const TOPO_COLS = ${COLS};
export const TOPO_GRID = ${JSON.stringify(grid)};
`;

const outPath = resolve(__dirname, "../src/topo-data.js");
writeFileSync(outPath, out, "utf8");
console.log(`Written → ${outPath}`);
