// Rasterises the brand SVGs (generated by gen-logo-svg.js) into the
// PNG/ICO files that browsers and PWA installers consume.
//
// Reads:
//   public/icons/favicon.svg            — main logo (rounded corners, 72% glyph)
//   public/icons/favicon-maskable.svg   — square, 56% glyph for Android masking
//
// Writes:
//   public/icons/icon-192.png           — PWA "any" 192×192
//   public/icons/icon-512.png           — PWA "any" 512×512
//   public/icons/icon-maskable.png      — PWA "maskable" 512×512
//   public/icons/apple-touch-icon.png   — iOS bookmark icon, 180×180. iOS
//                                         re-masks on its own, so we just
//                                         render the main logo.
//   public/favicon.ico                  — 32×32 PNG renamed .ico. Stays at the
//                                         site root so legacy crawlers that
//                                         blind-probe /favicon.ico get a hit.
//
// Usage: node scripts/gen-icons.js

import { readFile, writeFile } from 'fs/promises';
import sharp from 'sharp';

const main     = await readFile('public/icons/favicon.svg');
const maskable = await readFile('public/icons/favicon-maskable.svg');

await sharp(main,     { density: 384  }).resize(192, 192).png().toFile('public/icons/icon-192.png');
await sharp(main,     { density: 1024 }).resize(512, 512).png().toFile('public/icons/icon-512.png');
await sharp(maskable, { density: 1024 }).resize(512, 512).png().toFile('public/icons/icon-maskable.png');
await sharp(main,     { density: 1024 }).resize(180, 180).png().toFile('public/icons/apple-touch-icon.png');

const ico = await sharp(main, { density: 96 }).resize(32, 32).png().toBuffer();
await writeFile('public/favicon.ico', ico);

console.log('✓ public/icons/icon-192.png');
console.log('✓ public/icons/icon-512.png');
console.log('✓ public/icons/icon-maskable.png');
console.log('✓ public/icons/apple-touch-icon.png');
console.log('✓ public/favicon.ico');
